### ISSUE TITLE
May I ask for the versions of mmcv-full, mmdet, mmsegmentation and mmdet3d you used for HM-ViT?

### ISSUE THREAD

**Issue by dempsey-wen** [XHwind/HM-ViT#3]
Hi, thank you a lot for the great contributions you made in HM-ViT and your generous sharing of the codes. 

I met some compatibility problems when I had installed the related packages and tried to run the code. So could you provide the versions of mmcv-full, mmdet, mmsegmentation and mmdet3d you used for HM-ViT?

THANK YOU!

**Comment by Jerry-How** [comment]
> Hi, thank you a lot for the great contributions you made in HM-ViT and your generous sharing of the codes.
> 
> I met some compatibility problems when I had installed the related packages and tried to run the code. So could you provide the versions of mmcv-full, mmdet, mmsegmentation and mmdet3d you used for HM-ViT?
> 
> THANK YOU!

mmcv-full=1.4.0, mmdet=2.14.0, mmdet3d=0.17.1

**Comment by XHwind** [comment]
Thanks for reaching out, and thanks to Jerry for sharing the versions! Feel free to let me know if you run into any other issues!
