### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by pisces365** [XHwind/HM-ViT#4]
Hello. Thank you for your excellent work!
I noticed that the paper mentioned four 3090s. Does it mean that the entire training process of this project was completed with four 3090s?

**Comment by pisces365** [comment]
By the way, how long does one training session last?

**Comment by XHwind** [comment]
Hi Jiening. Yes, it is completed with 3090s. As mentioned in the paper, it involves multi-stage training and thus It usually takes one day to finish the training.
