### ISSUE TITLE
KeyError: 'camera' during model training

### ISSUE THREAD

**Issue by Knk324** [XHwind/HM-ViT#5]
I encountered a **KeyError: 'camera'** while trying to run the training script for my project. The error occurred during the forward pass of the model. 

I have run the following command cause i only have one gpu to use:
CUDA_VISIBLE_DEVICES=0 python opencood/tools/train_camera.py --hypes_yaml opencood/hypes_yaml/opcamera/cvt.yaml --model_dir opencood/logs/cvt_att_fuse

After that ,while during training, the following error occurs after building the dataset:
Traceback (most recent call last):
  File "opencood/tools/train_camera.py", line 234, in <module>
    main()
  File "opencood/tools/train_camera.py", line 175, in main
    ouput_dict = model(batch_data['ego'])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/HM-ViT/opencood/models/cross_view_transformer.py", line 36, in forward
    x = batch_dict['camera']
KeyError: 'camera'

The "Batch 0 keys: dict_keys(['ego'])" is the output from my extra code to print the dict information,which indicates that the batch data only contains ego data but is missing camera information.

I am looking for guidance on:
> Any additional checks or modifications that might ensure camera data is consistently available in batch_dict.

**Comment by XHwind** [comment]
Hi, thanks for the question! Please use `opencood/hypes_yaml/opcl/bevformer_point_pillar_hetero.yaml` for training HM-ViT. The HM-ViT used the Bevformer as the camera backbone.
